const AI_CONFIG={endpoint:""};
document.addEventListener("DOMContentLoaded",()=>{
  lucide.createIcons();
  const body=document.body,sidebar=document.getElementById("sidebar"),overlay=document.getElementById("overlay");
  const close=()=>{sidebar.classList.remove("open");overlay.classList.remove("open")};
  document.getElementById("openMenu").onclick=()=>{sidebar.classList.add("open");overlay.classList.add("open")};
  document.getElementById("closeMenu").onclick=close;overlay.onclick=close;
  const savedTheme=localStorage.getItem("control-red-theme");if(savedTheme==="dark")body.classList.add("dark");
  const updateThemeIcon=()=>{document.getElementById("themeIcon").setAttribute("data-lucide",body.classList.contains("dark")?"sun":"moon");lucide.createIcons()};updateThemeIcon();
  document.getElementById("themeToggle").onclick=()=>{body.classList.toggle("dark");localStorage.setItem("control-red-theme",body.classList.contains("dark")?"dark":"light");updateThemeIcon()};
  const years=[2014,2015,2016,2017,2018,2019,2020,2021,2022,2023],values=[44,57,51,69,62,76,70,85,79,94],bars=document.getElementById("mainBars");
  years.forEach((year,i)=>{const g=document.createElement("div");g.className="bar-group";g.innerHTML=`<i class="bar a" style="height:${values[i]}%"></i><i class="bar b" style="height:${values[i]*.62}%"></i><i class="bar c" style="height:${values[i]*.35}%"></i><span class="bar-year">${year}</span>`;bars.appendChild(g)});
  const vals=[38,55,48,75,62,81,69,98,78,88,67,92];document.querySelectorAll(".mini-bars").forEach((box,n)=>vals.forEach(v=>{const p=document.createElement("div");p.className="mini-pair";const scale=n===1?1.12:n===2?.95:1;p.innerHTML=`<i style="height:${Math.max(15,(v-13)*scale)}px"></i><i class="current" style="height:${v*scale}px"></i>`;box.appendChild(p)}));
  const refreshSubtitle=()=>{const m=document.getElementById("monthSelect").value.toLowerCase(),y=document.getElementById("yearSelect").value;document.getElementById("chartSubtitle").textContent=`Acumulado enero-${m} · referencia ${y}`};
  document.getElementById("monthSelect").onchange=refreshSubtitle;document.getElementById("yearSelect").onchange=refreshSubtitle;
  const metadata={dashboard:["Estadísticos 1","Evolución histórica de los principales indicadores de captación, distribución e intercambios de agua"],"informe-ia":["Informe IA Ejecutivo","Análisis directivo de los indicadores visibles y recomendaciones prioritarias"],estadisticos2:["Estadísticos 2","Pantalla estadística en preparación"],estadisticos3:["Estadísticos 3","Pantalla estadística en preparación"],estadisticos4:["Estadísticos 4","Pantalla estadística en preparación"]};
  document.querySelectorAll(".nav-item[data-tab]").forEach(b=>b.onclick=()=>{document.querySelectorAll(".nav-item").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.querySelectorAll(".tab-panel").forEach(x=>x.classList.remove("active"));const tab=b.dataset.tab,panel=document.getElementById(`panel-${tab}`);(panel||document.getElementById("panel-placeholder")).classList.add("active");const info=metadata[tab]||["Sección","Pantalla en preparación"];document.getElementById("pageTitle").textContent=info[0];document.getElementById("pageDescription").textContent=info[1];if(!panel)document.getElementById("placeholderTitle").textContent=info[0];close();lucide.createIcons()});
  document.getElementById("printReport").onclick=()=>window.print();
  document.getElementById("generateReport").onclick=generateExecutiveReport;
});
function getDashboardData(){const cards=[...document.querySelectorAll(".kpi")];return{month:document.getElementById("monthSelect").value,year:document.getElementById("yearSelect").value,metrics:cards.map(c=>({name:c.querySelector("span").textContent.trim(),value:c.querySelector("strong").textContent.trim(),trend:c.querySelector("footer b").textContent.trim(),detail:c.querySelector("footer small").textContent.trim()}))}}
function localExecutiveAnalysis(data,prompt){const m=Object.fromEntries(data.metrics.map(x=>[x.name,x]));return{summary:`En ${data.month.toLowerCase()} de ${data.year}, la red presenta una captación acumulada de ${m["Captada acumulada"].value} y una distribución estimada de ${m["Distribuida estimada"].value}. El balance de intercambios se sitúa en ${m["Balance de intercambios"].value}, mientras que la variación interanual alcanza ${m["Variación interanual"].value}. En conjunto, los indicadores muestran una evolución favorable, aunque conviene validar la sostenibilidad del crecimiento y revisar cualquier desviación entre captación, distribución e intercambios.${prompt?` El análisis se ha orientado a: ${prompt}`:""}`,strengths:[`La captación acumulada registra una tendencia de ${m["Captada acumulada"].trend}.`,`La distribución estimada mantiene una evolución de ${m["Distribuida estimada"].trend}.`,`El balance de intercambios permanece positivo y aporta flexibilidad operativa.`],risks:[`La variación interanual debe contrastarse con la demanda real y la estacionalidad.`,`Una diferencia sostenida entre captación y distribución puede requerir revisión técnica.`,`Los resultados dependen de la calidad y actualización de los datos de origen.`],actions:[`Revisar semanalmente el balance entre volumen captado y distribuido.`,`Comparar el período con la media de los últimos cinco años para identificar anomalías.`,`Incorporar alertas automáticas para desviaciones superiores al umbral operativo definido.`]}}
async function generateExecutiveReport(){const loading=document.getElementById("aiLoading"),button=document.getElementById("generateReport"),data=getDashboardData(),prompt=document.getElementById("aiPrompt").value.trim();loading.hidden=false;button.disabled=true;let result;try{if(AI_CONFIG.endpoint){const r=await fetch(AI_CONFIG.endpoint,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({data,prompt})});if(!r.ok)throw new Error(`HTTP ${r.status}`);result=await r.json()}else{await new Promise(r=>setTimeout(r,650));result=localExecutiveAnalysis(data,prompt)}}catch(e){console.error(e);result=localExecutiveAnalysis(data,prompt);result.summary+=` No fue posible conectar con el servicio de IA, por lo que se ha utilizado el análisis local.`}finally{loading.hidden=true;button.disabled=false}renderReport(data,result)}
function renderReport(data,result){document.getElementById("reportPeriod").textContent=`Período analizado: ${data.month} de ${data.year}`;document.getElementById("reportDate").textContent=new Intl.DateTimeFormat("es-ES",{dateStyle:"long"}).format(new Date());document.getElementById("reportSummary").textContent=result.summary;document.getElementById("reportKpis").innerHTML=data.metrics.map(x=>`<div><span>${x.name}</span><strong>${x.value}</strong></div>`).join("");document.getElementById("reportStrengths").innerHTML=result.strengths.map(x=>`<li>${x}</li>`).join("");document.getElementById("reportRisks").innerHTML=result.risks.map(x=>`<li>${x}</li>`).join("");document.getElementById("reportActions").innerHTML=result.actions.map((x,i)=>`<div class="action-item"><b>${i+1}</b><div><strong>${x}</strong><p>Acción propuesta para seguimiento técnico y directivo.</p></div></div>`).join("");lucide.createIcons();document.getElementById("executiveReport").scrollIntoView({behavior:"smooth",block:"start"})}
